import { DefaultTheme, DarkTheme as NavigationDarkTheme } from '@react-navigation/native';

export const LightTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    tabBarColor: '#E0E8FF',
    background: '#FFFFFF',
    text: '#000000',
    inputText: '#000000',
    icon: '#000000',
    containerBackground: '#E8E8E8',
    unitbackground: '#003BE2',
    submitBackground: '#003BE2',
    submitText: '#FFFFFF',
    plusColor: '#FFFFFF',
    activeButtonBackground: '#003BE2',
    inactiveButtonBackground: '#DEDEDE',
    activeButtonText: '#FFFFFF',
    inactiveButtonText: '#000000',
    settingBackground: 'gray',
    settingActiveBackground: '#003BE2',
    divider: '#000000',
    profileActionButton: '#E8E8E8',
    settingIcon: '#FFFFFF',
    radioActive: 'black',
    termsLink: '#1B83C5',
    FlightDetailIcons: "#FFFFFF",
    signupText: "#6187F4",
    userMessage:"#E8E8E8",
    botMessage:"#003BE2",
    messageInput:"#E8E8E8",
    dateInputContainer: "#E9E9E9",
    timerBackground: "#000000",
  },
};

export const CustomDarkTheme = {
  ...NavigationDarkTheme,
  colors: {
    ...NavigationDarkTheme.colors,
    tabBarColor: '#FFFFFF',
    background: '#101010',
    text: '#FFFFFF',
    inputText: '#000000',
    icon: '#FFFFFF',
    containerBackground: '#FFFFFF26',
    unitbackground: '#000000',
    submitBackground: '#FFFFFF',
    submitText: '#000000',
    plusColor: '#003BE2',
    activeButtonBackground: '#FFFFFF',
    inactiveButtonBackground: '#FFFFFF40',
    activeButtonText: '#000000',
    inactiveButtonText: '#FFFFFF',
    settingBackground: '#FFFFFF26',
    settingActiveBackground: '#FFFFFF',
    divider: '#FFFFFF',
    profileActionButton: '#FFFFFF',
    settingIcon: '#003BE2',
    radioActive: '#FFFFFF',
    termsLink: '#FFFFFF',
    FlightDetailIcons: "#000000",
    signupText: "#FFFFFF",
    userMessage:"#FFFFFF",
    botMessage:"#003BE2",
    messageInput:"rgba(255, 255, 255, 0.25)",
    dateInputContainer: "#FFFFFFE5",
    timerBackground: "#FFFFFF26",

  },
};

export const BlueTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    tabBarColor: '#FFFFFF',
    background: '#0F2452',
    text: '#FFFFFF',
    inputText: '#000000',
    icon: '#FFFFFF',
    containerBackground: '#FFFFFF26',
    unitbackground: '#000000',
    submitBackground: '#FFFFFF',
    submitText: '#000000',
    plusColor: '#003BE2',
    activeButtonBackground: '#FFFFFF',
    inactiveButtonBackground: '#FFFFFF40',
    activeButtonText: '#000000',
    inactiveButtonText: '#FFFFFF',
    settingBackground: '#FFFFFF40',
    settingActiveBackground: '#FFFFFF',
    divider: '#FFFFFF',
    profileActionButton: '#FFFFFF',
    settingIcon:'#003BE2',
    radioActive: '#FFFFFF',
    termsLink: '#FFFFFF',
    FlightDetailIcons: "#000000",
    signupText: "#FFFFFF",
    userMessage:"#FFFFFF",
    botMessage:"#003BE2",
    messageInput:"rgba(255, 255, 255, 0.25)",
    dateInputContainer: "#FFFFFFE5",
    timerBackground: "#FFFFFF26",


  },
};
